@startuml
!theme vibrant

title Customer

entity Customer {
    +customer_id: INT (PK, AUTO_INCREMENT)
    --
    first_name: VARCHAR(255)
    last_name: VARCHAR(255) NOT NULL
    email: VARCHAR(255) UNIQUE NOT NULL
    phone: VARCHAR(20)
}

@enduml