@startuml
concise "v1.0.0" as v1 
concise "v2.0.0" as v2 
concise "v3.0.0" as v3 
concise "v3.1.0" as v3_1

scale 31536000 as 180 pixels
use date format "yyyy-MM"

v1 is proposed

@2025/01/01
v1 is draft
v2 is proposed

@2025/07/01
v1 is active #PaleGreen /' #green;line:green;text:white '/
v2 is draft
v3 is proposed

@2026/01/01
v2 is active #PaleGreen
v3 is draft
v3_1 is proposed

@2026/07/01
v3 is active #PaleGreen
v3_1 is draft

@2027/01/01
v1 is deprecated
v3_1 is active #PaleGreen

@2027/07/01
v1 is retired
v2 is deprecated

@2028/01/01
v2 is retired
v3 is deprecated

@2028/07/01
v3 is retired

highlight 2026/07/01 to 2027/07/01 #Gold;line:DimGrey : 3 versions in production

@enduml