# Adding some PII and other flags

apiVersion: "v3.1.0"
kind: "DataContract"
version: "v0.2.0" # [A]
status: "active"
id: "34cae6d7-7648-38b2-8f66-8db79e1e2ce4"
description:
  usage: "Customer information including address for analytics"
name: "CustomerContract"
tenant: "ClimateQuantum"

schema:
  - logicalType: "object"
    name: "Customer"
    physicalName: "Customer"
    physicalType: "table"
    description: "Defines a customer according to the standard enterprise model." # [D]
    properties:
      - logicalType: "number"
        name: "customer_id"
        physicalName: "customer_id"
        physicalType: "SERIAL"
        primaryKey: true # [E]
        required: true # [F]
        description: "Customer id is always required." # [D]
      - logicalType: "string"
        name: "first_name"
        physicalName: "first_name"
        physicalType: "VARCHAR (255)"
      - logicalType: "string"
        name: "last_name"
        physicalName: "last_name"
        physicalType: "VARCHAR (255)"
        required: true # [F]
        tags:
          - pii
          - gdpr
        quality: # [G]
          - metric: nullValues # [H] [I]
            mustBeLessThan: 1
            unit: percent
            description: "There must be less than 1% of null values in the last name column."
      - logicalType: "string"
        name: "email"
        physicalName: "email"
        physicalType: "VARCHAR (255)"
        required: true [F]
        quality: # [G]
          - metric: nullValues # [H] [I]
            mustBeLessThan: 5
            unit: percent
            description: " There must be less than 5% of null values in the e-mail column. Historically e-mails were not collected."
          - metric: invalidValues # [H] [J]
            mustBe: 0
            description: "The value must be a valid email, there is no tolerance."
            arguments:
            pattern: "/^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/"
      - logicalType: "string"
        name: "phone"
        physicalName: "phone"
        physicalType: "VARCHAR (20)"
  - logicalType: "object"
    name: "AddressType"
    physicalName: "AddressType"
    physicalType: "table"
    properties:
      - logicalType: "number"
        name: "address_type_id"
        physicalName: "address_type_id"
        physicalType: "SERIAL"
        primaryKey: true
        required: true
      - logicalType: "string"
        name: "address_type"
        physicalName: "address_type"
        physicalType: "VARCHAR (20)"
        required: true
  - logicalType: "object"
    name: "Address"
    physicalName: "Address"
    physicalType: "table"
    properties:
      - logicalType: "number"
        name: "address_id"
        physicalName: "address_id"
        physicalType: "SERIAL"
        primaryKey: true
        required: true
      - logicalType: "number"
        name: "customer_id"
        physicalName: "customer_id"
        physicalType: "INT"
        required: true
      - logicalType: "string"
        name: "street1"
        physicalName: "street1"
        physicalType: "VARCHAR (255)"
        required: true
      - logicalType: "string"
        name: "street2"
        physicalName: "street2"
        physicalType: "VARCHAR (255)"
      - logicalType: "string"
        name: "city"
        physicalName: "city"
        physicalType: "VARCHAR (100)"
        required: true
      - logicalType: "string"
        name: "state"
        physicalName: "state"
        physicalType: "VARCHAR (100)"
      - logicalType: "string"
        name: "postal_code"
        physicalName: "postal_code"
        physicalType: "VARCHAR (20)"
      - logicalType: "string"
        name: "country_cd"
        physicalName: "country_cd"
        physicalType: "CHAR (2)"
        required: true
      - logicalType: "number"
        name: "address_type_id"
        physicalName: "address_type_id"
        physicalType: "INT"

team: # K
  name: "Customer Team”
  description: "Automatically generated"
  members:
    - username: "jgp"
      dateIn: "2025-07-07"
      name: "Jean-Georges Perrin"
      role: "DPO"

slaProperties: # [L]
  - property: retention
    value: 3
    unit: y
